#!/usr/bin/python
import sys,subprocess,os,shutil
from librodder import * #the magic words that make the program work now
debug = False
def interpreter(debug):
    if debug == True:
        while True:
            grhgghqahugsoauigigifjioifajoijfaojosjiojigrijoojiafofoajfojifaiojf = input('>>> ') #i swear to god if anyone names a variable this
            try:
                exec(grhgghqahugsoauigigifjioifajoijfaojosjiojigrijoojiafofoajfojifaiojf)
            except Exception as e:
                print(str(e))
    else:
        pass
if sys.argv[1] == "check":
    check()
if os.path.exists(os.getenv('HOME') + '/.config/rodder') == False: #eh, i'll keep this check for dirs in the actual wrapper for now
    os.makedirs(os.getenv('HOME') + '/.config/rodder')
if os.path.exists(os.getenv('HOME') + '/.config/rodder/repos') == False:
    os.makedirs(os.getenv('HOME') + '/.config/rodder/repos')
if os.path.exists(os.getenv('HOME') + '/.config/rodder/repos/master-repo-list.txt') == False:
    with open(os.getenv('HOME') + '/.config/rodder/repos/master-repo-list.txt', 'w') as f:
        f.write('https://github.com/ruthenic/rodder-repo')
if os.path.exists(os.getenv('HOME') + '/.local/bin') == False:
    os.makedirs(os.getenv('HOME') + '/.local/bin') #have to throw this in here to fix docker systems
if sys.argv[1] == "help" or sys.argv[1] == "":
    print("rodder is a package management system\n")
    print("rodder install - installs program from current repos")
    print("rodder update - pulls newest version of repo file")
    print("rodder remove - uninstall program") #god this needs an update, but guess who can't be fucked
    exit()
elif sys.argv[1] == "update":
    update()
elif sys.argv[1] == "install":
    install(sys.argv[2]) #rodder install template; sys.argv[2] == template
elif sys.argv[1] == "remove":
    remove(sys.argv[2])
elif sys.argv[1] == 'list':
    list()
elif sys.argv[1] == 'repo': #here is where the code for managing repos starts
    if sys.argv[2] == 'list':
        repo.list
    elif sys.argv[2] == 'add':
        repo.add(sys.argv[3])
        with open(os.getenv('HOME') + '/.config/rodder/repos/master-repo-list.txt', 'a') as f:
            f.write('\n' + repo)
    elif sys.argv[2] == 'reset':
        repo.reset()
    elif sys.argv[2] == 'remove':
        repo.remove(sys.argv[3])
elif sys.argv[1] == 'search':
    search()
